### ISSUE TITLE
Enable https in gh-pages

### ISSUE THREAD

**Issue by liske** [elan-ev/bigbluebutton-map#47]
Could you please enable the "Enforce HTTPS" option in the github pages settings?

![image](https://user-images.githubusercontent.com/372458/113706038-7c76d200-96de-11eb-9906-46497e8e6145.png)

**Comment by tibroc** [comment]
Unfortunately, this is currently not supported by github for the DNS setup with multiple CNAME entries we have at UOS. So we won't act on this for now.
